// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/task/complete.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/task/complete.go -destination=internal/usecases/task/mocks/complete.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/task-manager-service-go/internal/platform/errors"
	task "github.com/tapiaw38/task-manager-service-go/internal/usecases/task"
	gomock "go.uber.org/mock/gomock"
)

// MockCompleteUsecase is a mock of CompleteUsecase interface.
type MockCompleteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCompleteUsecaseMockRecorder
	isgomock struct{}
}

// MockCompleteUsecaseMockRecorder is the mock recorder for MockCompleteUsecase.
type MockCompleteUsecaseMockRecorder struct {
	mock *MockCompleteUsecase
}

// NewMockCompleteUsecase creates a new mock instance.
func NewMockCompleteUsecase(ctrl *gomock.Controller) *MockCompleteUsecase {
	mock := &MockCompleteUsecase{ctrl: ctrl}
	mock.recorder = &MockCompleteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompleteUsecase) EXPECT() *MockCompleteUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCompleteUsecase) Execute(arg0 context.Context, arg1 string, arg2 task.CompleteInput) (*task.CompleteOutput, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*task.CompleteOutput)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCompleteUsecaseMockRecorder) Execute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCompleteUsecase)(nil).Execute), arg0, arg1, arg2)
}
