// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/task/create.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/task/create.go -destination=internal/usecases/task/mocks/create.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/task-manager-service-go/internal/platform/errors"
	task "github.com/tapiaw38/task-manager-service-go/internal/usecases/task"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateUsecase is a mock of CreateUsecase interface.
type MockCreateUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUsecaseMockRecorder
	isgomock struct{}
}

// MockCreateUsecaseMockRecorder is the mock recorder for MockCreateUsecase.
type MockCreateUsecaseMockRecorder struct {
	mock *MockCreateUsecase
}

// NewMockCreateUsecase creates a new mock instance.
func NewMockCreateUsecase(ctrl *gomock.Controller) *MockCreateUsecase {
	mock := &MockCreateUsecase{ctrl: ctrl}
	mock.recorder = &MockCreateUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUsecase) EXPECT() *MockCreateUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUsecase) Execute(arg0 context.Context, arg1 task.CreateInput) (*task.CreateOutput, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*task.CreateOutput)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUsecase)(nil).Execute), arg0, arg1)
}
