// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/task/delete.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/task/delete.go -destination=internal/usecases/task/mocks/delete.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/task-manager-service-go/internal/platform/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteUsecase is a mock of DeleteUsecase interface.
type MockDeleteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUsecaseMockRecorder
	isgomock struct{}
}

// MockDeleteUsecaseMockRecorder is the mock recorder for MockDeleteUsecase.
type MockDeleteUsecaseMockRecorder struct {
	mock *MockDeleteUsecase
}

// NewMockDeleteUsecase creates a new mock instance.
func NewMockDeleteUsecase(ctrl *gomock.Controller) *MockDeleteUsecase {
	mock := &MockDeleteUsecase{ctrl: ctrl}
	mock.recorder = &MockDeleteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUsecase) EXPECT() *MockDeleteUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteUsecase) Execute(arg0 context.Context, arg1 string) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteUsecase)(nil).Execute), arg0, arg1)
}
