// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/task/get.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/task/get.go -destination=internal/usecases/task/mocks/get.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/task-manager-service-go/internal/platform/errors"
	task "github.com/tapiaw38/task-manager-service-go/internal/usecases/task"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUsecase is a mock of GetUsecase interface.
type MockGetUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUsecaseMockRecorder
	isgomock struct{}
}

// MockGetUsecaseMockRecorder is the mock recorder for MockGetUsecase.
type MockGetUsecaseMockRecorder struct {
	mock *MockGetUsecase
}

// NewMockGetUsecase creates a new mock instance.
func NewMockGetUsecase(ctrl *gomock.Controller) *MockGetUsecase {
	mock := &MockGetUsecase{ctrl: ctrl}
	mock.recorder = &MockGetUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUsecase) EXPECT() *MockGetUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUsecase) Execute(arg0 context.Context, arg1 string) (*task.GetOutput, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*task.GetOutput)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUsecase)(nil).Execute), arg0, arg1)
}
